<?php

namespace Database\Seeders;

use App\Models\SanPham;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SanPhamSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('san_phams')->delete();

        DB::table('san_phams')->insert([
            [
                'ten_san_pham'            => 'iPhone 17 Pro Max',
                'mo_ta'                   => 'Màn hình Super Retina XDR 6.9", chip A19 Pro, camera 48MP thế hệ mới.',
                'ma_san_pham'             => 'IP17-PROMAX-256',
                'gia_nhap'                => 28000000,
                'gia_ban'                 => 34990000,
                'so_luong'                => 50,
                'trang_thai'              => true,
                'danh_muc'                => 'Điện thoại',
                'ngay_nhap'               => '2026-08-01',
                'gio_mo_ban'              => '08:00:00',
                'phan_tram_giam_gia'      => 10.0,
                'san_pham_noi_bat'        => true,
                'ngay_bat_dau_khuyen_mai' => '2026-08-15 08:00:00',
                'so_luot_xem'             => 1520,
                'ghi_chu'                 => 'Hàng nhập khẩu chính hãng Apple',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400',
            ],
            [
                'ten_san_pham'            => 'Samsung Galaxy S26 Ultra',
                'mo_ta'                   => 'Camera 200MP zoom quang học 100x, bút S-Pen tích hợp AI, màn hình Dynamic AMOLED 2X.',
                'ma_san_pham'             => 'SS26-ULTRA-512',
                'gia_nhap'                => 22000000,
                'gia_ban'                 => 27990000,
                'so_luong'                => 30,
                'trang_thai'              => true,
                'danh_muc'                => 'Điện thoại',
                'ngay_nhap'               => '2026-08-05',
                'gio_mo_ban'              => '09:00:00',
                'phan_tram_giam_gia'      => 8.0,
                'san_pham_noi_bat'        => true,
                'ngay_bat_dau_khuyen_mai' => '2026-08-10 09:00:00',
                'so_luot_xem'             => 980,
                'ghi_chu'                 => 'Bảo hành chính hãng 24 tháng',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400',
            ],
            [
                'ten_san_pham'            => 'MacBook Pro 16 M4 Pro',
                'mo_ta'                   => 'Chip Apple M4 Pro 12 nhân CPU, màn hình Liquid Retina XDR 16.2", pin 22 giờ.',
                'ma_san_pham'             => 'MBP16-M4PRO-24G',
                'gia_nhap'                => 52000000,
                'gia_ban'                 => 64990000,
                'so_luong'                => 15,
                'trang_thai'              => true,
                'danh_muc'                => 'Laptop',
                'ngay_nhap'               => '2026-07-20',
                'gio_mo_ban'              => '08:30:00',
                'phan_tram_giam_gia'      => 5.0,
                'san_pham_noi_bat'        => true,
                'ngay_bat_dau_khuyen_mai' => '2026-08-01 00:00:00',
                'so_luot_xem'             => 760,
                'ghi_chu'                 => 'Màu Space Black, RAM 24GB, SSD 512GB',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400',
            ],
            [
                'ten_san_pham'            => 'iPad Pro 13 M4',
                'mo_ta'                   => 'Màn hình OLED Ultra Retina XDR 13", chip M4, hỗ trợ Apple Pencil Pro.',
                'ma_san_pham'             => 'IPAD-PRO13-M4-256',
                'gia_nhap'                => 25000000,
                'gia_ban'                 => 31990000,
                'so_luong'                => 20,
                'trang_thai'              => true,
                'danh_muc'                => 'Máy tính bảng',
                'ngay_nhap'               => '2026-07-25',
                'gio_mo_ban'              => '09:30:00',
                'phan_tram_giam_gia'      => 7.0,
                'san_pham_noi_bat'        => true,
                'ngay_bat_dau_khuyen_mai' => '2026-08-05 09:00:00',
                'so_luot_xem'             => 540,
                'ghi_chu'                 => 'WiFi + Cellular, màu Silver',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400',
            ],
            [
                'ten_san_pham'            => 'Apple Watch Ultra 3',
                'mo_ta'                   => 'Vỏ titan 49mm, GPS chính xác cao, pin 72 giờ, chống nước 100m.',
                'ma_san_pham'             => 'AW-ULTRA3-49MM',
                'gia_nhap'                => 18000000,
                'gia_ban'                 => 23490000,
                'so_luong'                => 25,
                'trang_thai'              => true,
                'danh_muc'                => 'Đồng hồ thông minh',
                'ngay_nhap'               => '2026-08-08',
                'gio_mo_ban'              => '10:00:00',
                'phan_tram_giam_gia'      => 0.0,
                'san_pham_noi_bat'        => false,
                'ngay_bat_dau_khuyen_mai' => '2026-08-08 10:00:00',
                'so_luot_xem'             => 320,
                'ghi_chu'                 => 'Bao gồm dây đeo Alpine và Oceanic',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400',
            ],
            [
                'ten_san_pham'            => 'AirPods Pro 3',
                'mo_ta'                   => 'Chống ồn chủ động thế hệ 3, chip H3, âm thanh không gian cá nhân hóa.',
                'ma_san_pham'             => 'AIRPODS-PRO3-USB',
                'gia_nhap'                => 4500000,
                'gia_ban'                 => 6490000,
                'so_luong'                => 80,
                'trang_thai'              => true,
                'danh_muc'                => 'Phụ kiện',
                'ngay_nhap'               => '2026-08-10',
                'gio_mo_ban'              => '08:00:00',
                'phan_tram_giam_gia'      => 12.0,
                'san_pham_noi_bat'        => false,
                'ngay_bat_dau_khuyen_mai' => '2026-08-20 08:00:00',
                'so_luot_xem'             => 1100,
                'ghi_chu'                 => 'Hộp sạc MagSafe USB-C',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400',
            ],
            [
                'ten_san_pham'            => 'Dell XPS 15 OLED',
                'mo_ta'                   => 'Màn hình OLED 15.6" 4K+, Intel Core Ultra 9 185H, RAM 32GB, RTX 4070.',
                'ma_san_pham'             => 'DELL-XPS15-OLED-32G',
                'gia_nhap'                => 45000000,
                'gia_ban'                 => 56990000,
                'so_luong'                => 10,
                'trang_thai'              => true,
                'danh_muc'                => 'Laptop',
                'ngay_nhap'               => '2026-07-15',
                'gio_mo_ban'              => '09:00:00',
                'phan_tram_giam_gia'      => 6.0,
                'san_pham_noi_bat'        => false,
                'ngay_bat_dau_khuyen_mai' => '2026-08-01 09:00:00',
                'so_luot_xem'             => 430,
                'ghi_chu'                 => 'Màu Platinum, SSD 1TB NVMe',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400',
            ],
            [
                'ten_san_pham'            => 'Xiaomi 15 Pro',
                'mo_ta'                   => 'Ống kính Leica Summilux thế hệ mới, sạc siêu nhanh 120W, chip Snapdragon 8 Elite.',
                'ma_san_pham'             => 'XM15-PRO-256',
                'gia_nhap'                => 13500000,
                'gia_ban'                 => 17490000,
                'so_luong'                => 0,
                'trang_thai'              => false,
                'danh_muc'                => 'Điện thoại',
                'ngay_nhap'               => '2026-07-01',
                'gio_mo_ban'              => '10:00:00',
                'phan_tram_giam_gia'      => 5.0,
                'san_pham_noi_bat'        => false,
                'ngay_bat_dau_khuyen_mai' => '2026-07-01 10:00:00',
                'so_luot_xem'             => 450,
                'ghi_chu'                 => 'Hết hàng đợt 1, đang nhập thêm',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400',
            ],
            [
                'ten_san_pham'            => 'Sony WH-1000XM6',
                'mo_ta'                   => 'Tai nghe chống ồn cao cấp thế hệ mới nhất của Sony, âm thanh Hi-Res, pin 35 giờ.',
                'ma_san_pham'             => 'SONY-WH1000XM6-BLK',
                'gia_nhap'                => 6500000,
                'gia_ban'                 => 8990000,
                'so_luong'                => 35,
                'trang_thai'              => true,
                'danh_muc'                => 'Phụ kiện',
                'ngay_nhap'               => '2026-08-02',
                'gio_mo_ban'              => '08:00:00',
                'phan_tram_giam_gia'      => 15.0,
                'san_pham_noi_bat'        => true,
                'ngay_bat_dau_khuyen_mai' => '2026-08-12 08:00:00',
                'so_luot_xem'             => 820,
                'ghi_chu'                 => 'Hàng chính hãng Sony Việt Nam',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
            ],
            [
                'ten_san_pham'            => 'Asus ROG Zephyrus G16',
                'mo_ta'                   => 'Laptop Gaming mỏng nhẹ, màn hình ROG Nebula OLED 240Hz, Intel Core Ultra 9, RTX 4080.',
                'ma_san_pham'             => 'ROG-G16-GU605-OLED',
                'gia_nhap'                => 48000000,
                'gia_ban'                 => 59990000,
                'so_luong'                => 12,
                'trang_thai'              => true,
                'danh_muc'                => 'Laptop',
                'ngay_nhap'               => '2026-08-05',
                'gio_mo_ban'              => '09:00:00',
                'phan_tram_giam_gia'      => 5.0,
                'san_pham_noi_bat'        => true,
                'ngay_bat_dau_khuyen_mai' => '2026-08-10 09:00:00',
                'so_luot_xem'             => 640,
                'ghi_chu'                 => 'Tặng kèm chuột ROG Glacier White',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400',
            ],
            [
                'ten_san_pham'            => 'Samsung Galaxy Tab S10 Ultra',
                'mo_ta'                   => 'Màn hình Dynamic AMOLED 2X 14.6", chip Dimensity 9300+, bút S-Pen cải tiến AI.',
                'ma_san_pham'             => 'SS-TABS10-ULTRA-5G',
                'gia_nhap'                => 21000000,
                'gia_ban'                 => 26990000,
                'so_luong'                => 18,
                'trang_thai'              => true,
                'danh_muc'                => 'Máy tính bảng',
                'ngay_nhap'               => '2026-08-07',
                'gio_mo_ban'              => '08:30:00',
                'phan_tram_giam_gia'      => 10.0,
                'san_pham_noi_bat'        => false,
                'ngay_bat_dau_khuyen_mai' => '2026-08-15 08:30:00',
                'so_luot_xem'             => 410,
                'ghi_chu'                 => 'Hỗ trợ phím Book Cover Keyboard',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=400',
            ],
            [
                'ten_san_pham'            => 'Garmin Fenix 8 Sapphire',
                'mo_ta'                   => 'Đồng hồ thông minh thể thao chuyên nghiệp, màn hình AMOLED 47mm, bản đồ Offline.',
                'ma_san_pham'             => 'GARMIN-FENIX8-SAPPHIRE',
                'gia_nhap'                => 22000000,
                'gia_ban'                 => 28490000,
                'so_luong'                => 22,
                'trang_thai'              => true,
                'danh_muc'                => 'Đồng hồ thông minh',
                'ngay_nhap'               => '2026-08-11',
                'gio_mo_ban'              => '09:00:00',
                'phan_tram_giam_gia'      => 0.0,
                'san_pham_noi_bat'        => true,
                'ngay_bat_dau_khuyen_mai' => '2026-08-11 09:00:00',
                'so_luot_xem'             => 530,
                'ghi_chu'                 => 'Kính Sapphire chống xước tuyệt đối',
                'hinh_anh'                => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
            ],
        ]);
    }
}

